name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    permissions:
      actions: read
      checks: write
      contents: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          registry: docker.io

      - name: Release build
        id: release_build
        uses: docker/build-push-action@v3
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm/v6,linux/arm64
          build-args: |
            Version=${{ github.ref_name }}
            GitCommit=${{ github.sha }}
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/weather_exporter:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/weather_exporter:latest
